# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name=b'#Views'),
        ),
        migrations.AlterField(
            model_name='album',
            name='counter',
            field=models.PositiveSmallIntegerField(default=0, editable=False, null=True, verbose_name=b'#Images'),
        ),
    ]
