# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20160822_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='gviews',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name=b'GViews'),
        ),
    ]
